name: scrolling_years_calendar
description: A calendar widget to easily scroll through the years, allowing for customizations to fit your design.
version: 1.3.1
homepage: https://github.com/mennorenkens/flutter_scrolling_calendar

environment:
  sdk: ">=3.5.0"

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0

dev_dependencies:
  flutter_test:
    sdk: flutter
